### ISSUE TITLE
Refactor session state

### ISSUE THREAD

**Issue by bradunov** [bradunov/shkola#23]
Currently session state stores the entire page_param object, which contains parts of the page params that are not part of the state, but of each request (e.g. root, op). This should be refactored so that we store in the session only parts that are necessary for the state. We should refactor page_params into page_params.session and page_params.request.

**Comment by vladap2013** [comment]
I think we don't need page_params.session. Session data should be read/written directly from the session object. And page_params should not be stored in the session.
